### ISSUE TITLE
Cactus can grow even when there is a block next to it

### ISSUE THREAD

**Issue by RobertHDPotatoes** [InZan17/Unloaded-Activity-Fabric#20]
Fabric 1.20.2

If you grow cactus, but don't want it to grow taller than 1 block you can put walls around the cactus starting at the second level of it so that when the cactus grows, it will instantly break. This is commonly used in farms, but there is a rare chance that when unloaded activity grows the cactus, it will ignore the fact that there is a block next to it and not break.

**Comment by InZan123** [comment]
I've encountered this issue too when testing but I wasn't able to fix it since I wanted it to still grow but then break naturally. I could also try to force it to break if the conditions are right, but I'll probably try to fix it for the next update.

**Comment by RobertHDPotatoes** [comment]
Alright, thank you. It's not really that big of an issue, because eventually when it tries to grow again it will break, but I just wanted to make sure you were aware of it.

**Comment by InZan17** [comment]
Sorry I forgot about this issue for a while. This has now been fixed in the latest version 0.5.4.
